#!/bin/bash
#BSUB -J test_G_1
#BSUB -q normal
#BSUB -o test_G-o.%J
#BSUB -e test_G-e.%J
#BSUB -n 480
#BSUB -R rusage[mem=150G]
#BSUB -R span[ptile=48]

#export OMP_NUM_THREADS=45

echo job start time is `date`
echo `hostname`

echo "start: ${SYEAR}" `date`  >> log.txt

#mpirun  -np 720 ./mksrfdata.x test_G.nml
#mpirun  -np 720 ./mkinidata.x test_G.nml
mpirun  -np 480 ./colm.x test_G.nml


echo "end:   ${SYEAR}" `date`  >> log.txt

# mv ${LOGOUT} log_CaMa-${CYR}.txt

#================================================
# (6) manage spin up

# if curent spinup time $ISP < required spinup time $NSP
#   copy the restart file restart$(IYR+1) to restart${IYR}
#   copy the outputs to directory "${IYR}-sp1"



exit 0
echo job end time is `date`

